/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "interface_constants.h"



const interfaceConstants g_interface_constants;

interfaceConstants::interfaceConstants() {
}



