/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef interface_CONSTANTS_H
#define interface_CONSTANTS_H

#include "interface_types.h"



class interfaceConstants {
 public:
  interfaceConstants();

};

extern const interfaceConstants g_interface_constants;



#endif
